### ISSUE TITLE
Leaking Source

### ISSUE THREAD

**Issue by almazangc** [QueenChristina/gd_dialog#4]
When the Player interacts with NPC
-Create an orphan nodes that does not get deleted.

![image_2021-12-03_192053](https://user-images.githubusercontent.com/59057047/144594351-c30aeb11-e6cd-4390-8ee6-bfd9994190a9.png)
Initial

![image](https://user-images.githubusercontent.com/59057047/144594368-c5fb9afc-2221-405a-bb99-e5bcd6dd4b36.png)
Interacting once

![image](https://user-images.githubusercontent.com/59057047/144594435-5ae9745d-165b-4323-a46b-9fddaf75a133.png)
More interaction, the orphan node keeps stacking

![image](https://user-images.githubusercontent.com/59057047/144594494-efc3b506-164d-4097-ae19-c008e17193d6.png)
By setting project editor --verbose command prompt displays the leak

**Comment by QueenChristina** [comment]
Thank you so much for bringing up this issue! This is my first time learning about orphan nodes in Godot, so I learned something new today thanks to you.

I've investigated and turns out DialogNode and RichTextLabel instances were being orphaned and not freed properly -- I've made some changes, and the issue should be fixed now.
